export const constants = {
  DEFAULT_LANGUAGE: 'en',
  PAGE_TITLE_PREFIX: 'new clinic',
  LOGIN_SUCCESS_REDIRECT_URL: '/dashbored',
  MIN_LENGTH_TEXT_INPUT: 8,
  MAX_LENGTH_TEXT_INPUT: 191,
  MAX_LENGTH_TEXTAREA: 16777215,
  TABLE_ROWS_LENGTH: 10,
  DATA_LIMIT: 12,
  NUMBER_PHONE: 11,
};
